/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

let factors = 0, num = 1, sequence = 1;
while(factors < 500){
    num++;
    sequence += num;
    factors = getFactors(sequence);
    if (factors > 100)
        console.log("sequence: " + sequence + " - factors: " + factors);
}

console.log(factors)


function getFactors(num){
    let cont = 0;
    for(let i = 0 ; i <= num ; i++){
        if(num % i == 0){
            cont++;
        }
    }
    return cont;
}